### PR TITLE
A couple of test cases with NaN's thrown in

### PR DESCRIPTION
**Pull request by lukemcgregor**
The first of these fails for me, I think its due to your sort method

### CODE REVIEW

**Comment by d4rkr00t** [comment]
What would be expected behaviour for you dealing with NaN? Would you prefer treating them as 0?

**Comment by lukemcgregor** [comment]
Wow fast reply 👍 

I think I would expect them to be sorted below int.min, but I cant really justify that with a reason? 

Wherever they get put I would expect them to be stably sorted regardless of where they appear in the original array (eg the two tests I added should return the same result).

**Comment by d4rkr00t** [comment]
Oh, ok, probably should treat them as `Number.NEGATIVE_INFINITY`. If you are up for fixing sorting to treat NaNs as negative infinity and sending a PR, that would be awesome. Or I can have a look a bit later today.

**Comment by d4rkr00t** [comment]
Released as https://github.com/d4rkr00t/percentile/releases/tag/v1.2.1

**Pull request merged**
